import { ApiProperty } from '@nestjs/swagger';
import {
  IsEthereumAddress,
  IsHexadecimal,
  IsString,
  Length,
} from 'class-validator';

export class SignInDTO {
  @ApiProperty({
    description: 'Ethereum address of the user trying to sign in',
    example: '0x1234567890abcdef1234567890abcdef12345678',
  })
  @IsEthereumAddress()
  auditorAddress: string;

  @ApiProperty({
    description: 'Signature generated by the user to verify the message',
    example:
      '0xabcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890',
  })
  @IsString()
  @IsHexadecimal()
  @Length(128, 256)
  signature: string;
}
