import { ApiProperty } from '@nestjs/swagger';

export class SignInDTO {
  @ApiProperty({
    description: 'Ethereum address of the user trying to sign in',
    example: '0x1234567890abcdef1234567890abcdef12345678',
  })
  address: string;

  @ApiProperty({
    description: 'Signature generated by the user to authenticate the request',
    example:
      '0xabcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890',
  })
  signature: string;

  @ApiProperty({
    description:
      'Nonce used to ensure the request is unique and to prevent replay attacks',
    example: 'a3f1c9e2',
  })
  nonce: string;
}
